### PR TITLE
Feature suggestion: Implementing URL protection via a filter

### PR DESCRIPTION
**Pull request by hugovalk**
In order to simplify application development and reducing the risk on mistakes, I think it is useful to have url protection as a filter. 

I have provided an example of how this could work in the scala demo app. Once this solution is approved as being useful, I can perform the necessary changes in the play-pac4j project and update the demo projects accordingly. 

Features:
 - filter to configure in your Play Filter chain
 - configurable via application.conf
   - rules are applied top to bottom - first matching rule wins
   - rules consist of regex and authorizer name

Still to be done: 
 - configuration of the client name. 

What do people think about this?

### CODE REVIEW

**Comment by hugovalk** [comment]
Check the class `Application2.scala` to see how this cleans up the code.

**Comment by leleuj** [comment]
In fact, Play is the only pac4j library which does not use a filter to protect resources but an annotation in Java and a function in Scala, associated to a specific action.
I'm **very interested** by your proposal, but I would not limit the implementation to authorizations only, but also to authentication.
Seeing your solution, it seems you based your filter on the existing `RequiresAuthenticationAction`, which is a good way to limit the code and avoid any mistake.

For me, this filter must also deal with authentication. So the syntax must take that into account. Something like:

```
security {
   rules = [
     {"/facebook/.*" = "FacebookClient"}
     {"/facebookadmin/.*" = "FacebookClient,TwitterClient", "admin"}
   ]
} 
```

Behind the scene, each rule would be associated to a `RequiresAuthenticationAction`.

Does it make sense? If you agree, I will branch a 2.0.x and update the master to 2.1.0 for your evolution.

**Comment by hugovalk** [comment]
That certainly makes sense. I had not added the authentication in this first draft, waiting for your feedback. 
I will then provide an updated implementation in the play-pac4j framework and open a new pull request. 

With respect to configuration, would it make sense to make this more explicit:

    security {
      rules = [
        {"/.*admin.*" = {
          authorizers = "admin"
          clients = ["FormClient"]
        }}
        {"/.*custom.*" = {
          authorizers = "custom, admin"
          clients = ["FacebookClient, FormClient"]
        }}
        {"/protected.*" = {
          authorizers = "_authenticated_"
        }}
        {"/.*" = {
          authorizers = "_anonymous_"
        }}
      ]
    }

It works like this:
 - rules are applied top to bottom: first match wins
 - clientName and authorizerName are configured
 - special value _authenticated_ means authentication is required, and null will be inserted as authorizerName (not specifying any role) (no authorization)
 - special value _anonymous_ means no authentication (and thus no authorization)

**Comment by leleuj** [comment]
I created the branch 2.0.x and updated the master to version 2.1.0 for your feature.

I don't think that the `_anonymous_` section is of any use. I would just keep `clients`, ` authorizers` and the special: `_authenticated_` keyword.
More generally, I think that the `clients` and ` authorizers` keywords are good ones (better than `clientName` and `authorizerName` I used so far) and I'm thinking about renaming `RequiresAuthenticationAction` as `SecureAction` somehow following your `SecureFilter`: any opinion on this?

**Comment by hugovalk** [comment]
Sounds like a great idea w.r.t. the naming. 

I do not agree about _anonymous_. You need this to override a generic rule. 

Good practice would be a config like this:

.*healthcheck.*=_anonymous_
.*admin.*= admin
.* = _authenticated_

**Comment by leleuj** [comment]
You're right with this example. The `.* = _anonymous_` is just not required at the end as it's implicit, isn't it?

**Comment by hugovalk** [comment]
My first example was bad, having `.* = _anonymous` at the end did indeed not make any sense. But in the latest example it is needed.

**Comment by leleuj** [comment]
OK. Perfect.

**Comment by hugovalk** [comment]
This PR should now include everything for the SecurityFilter, including testcases and fixes #28

**Comment by leleuj** [comment]
@hugovalk This is where I realized I never merged your pull request for filter.

I just upgraded the demo with pac4j v1.9.

I saw you had tests in this PR. In play-pac4j, I have completely rewritten the basic existing tests to have something very relevant now. I think it would make sense if you could add some tests in play-pac4j for the `SecurityFilter` and update this demo (again) to match the latest state.

Thanks

**Comment by leleuj** [comment]
@hugovalk I will release the new play-pac4j 2.3 version next week: do you have some time to add a test for the filter? And maybe update this demo?

**Comment by hugovalk** [comment]
Hi,
I made a mistake, by deleting my branch which contained this pull request.
Can you still merge it, so I can see if I can add some tests.

Op vr 3 jun. 2016 om 09:22 schreef LELEU Jérôme <notifications@github.com>:

**Comment by hugovalk** [comment]
The tests I have here are more integration tests. They use a running application with a proper application.conf and routes file. This is not straightforward to do in the play-pac4j project. 

But at least all code is now properly merged again.

**Comment by leleuj** [comment]
I was writing a message to you as your branch still exists in your repo: https://github.com/hugovalk/play-pac4j-scala-demo/tree/filter but I see you've found it back by yourself ;-)

Having tests for the filter directly in play-pac4j would be great also! Thanks

**Comment by leleuj** [comment]
@hugovalk : the demo is now built by Travis and tests are successfully played.

**Pull request merged**
