### PR TITLE
Update to play-pac4j version 4.0.0-SNAPSHOT for Play 2.6.2

### PR DESCRIPTION
**Pull request by taggiasco**
First demo project to be updated.

### CODE REVIEW

**Comment by leleuj** [comment]
Thanks for the update!

Though, the build is broken because of failing tests (`SecuritySpec`): Can you take a look? Thx

**Comment by taggiasco** [comment]
@leleuj 
I managed to remove the "double" application, but now there are other errors telling me the play cache is not allive (through an org.pac4j.core.exception.TechnicalException).
I really don't see how to correct that. Any idea ? (I can push my change in SecuritySpec if needed)

**Comment by leleuj** [comment]
Yes, please update the PR so that I can see the remaining error...

**Comment by leleuj** [comment]
@taggiasco I've spent a few hours struggling with the tests.

The `HomePageSpec` failed because of a bug I fixed on the cookie management: https://github.com/pac4j/play-pac4j/pull/188/files

The "The play Cache is not alive (STATUS_SHUTDOWN)" error comes from the fact that the `FakeCache` is not injected and that the default `EhCache` is used instead. And the injection fails because the `PlayCacheSessionStore` expects a `play.cache.SyncCacheApi` while the `FakeCache` is a `play.api.cache.SyncCacheApi`. So you should rewrite the `FakeCache` to implement the `play.cache.SyncCacheApi` (certainly a Java class instead of a Scala one).

**Comment by leleuj** [comment]
I tested it and the demo works after a minor fix. Let's merge this work and fix the tests later on.

**Comment by leleuj** [comment]
@taggiasco here is the fix for the demo to work: https://github.com/pac4j/play-pac4j-scala-demo/commit/e3d17508ef89b44bc94d51b9aeb3776a1f810b51
Thanks for your help

@hugovalk would you mind helping us in fixing the tests? I've seen that the `FakeCache` is not injected as the binding must happen for the `play.cache.SyncCacheApi` interface and not for the `play.api.cache.SyncCacheApi` trait...

**Comment by taggiasco** [comment]
@leleuj Thank you for the fix. And sorry for that. I did not find enough time this week for this.

**Pull request merged**
